sudo: required

env:
  global:
  - OPENSHIFT_VERSION=3.6.1
  - OPENSHIFT_COMMIT=008f2d5 # always update when bumping $OPENSHIFT_VERSION

services:
  - docker

jobs:
  include:
    # - stage: verify source code
    #   script: ./tools/travis/verify_source_code.sh
    - stage: deploy
      script: ./tools/travis/setup.sh
    # - stage: package
    #   script: ./tools/travis/package_source_code.sh

after_failure:
  - echo "failed build"
  - ./tools/travis/cleanup.sh
